# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  wzcomparerr2server:
    image: wzcomparerr2server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "7209:443"
      - "5285:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7209
      - ASPNETCORE_Kestrel__Certificates__Default__Password=270e9908-480d-4647-a482-4503e3492e57
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
    volumes:
      - ./https/aspnetapp.pfx:/app/https/aspnetapp.pfx:ro
      - WzData:/app/Data
volumes:
  WzData:
    external: true